name: builddb
run-name: build jdk9 codeql db
on: [push]
  # schedule:
  #   - cron: '0 0 31 * *'

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build-db:
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
    steps:
      - name: Install deps
        run: uname -a && sudo apt update && sudo apt install -y wget git gcc g++ make file unzip zip libx11-dev \
          libxrender-dev libxtst-dev libxt-dev libcups2-dev libfreetype6-dev libasound2-dev libfontconfig1-dev
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Clone jdk9 src
        run: git clone --depth=1 https://github.com/openjdk/jdk9u
      - name: Configure && Make
        run: cd jdk9u && bash configure --disable-warnings-as-errors && make images && cd -
      - name: Initialize CodeQL
        run: |
          wget https://github.com/github/codeql-cli-binaries/releases/download/v2.13.3/codeql-linux64.zip && 
          ls -lh &&
          unzip codeql-linux64.zip && ls -lh codeql
      - name: Create codeql db
        run: codeql/codeql database create jdk9db --language=java --source-root jdk9u --command='make images'
      - name: Upload db
        uses: actions/upload-artifact@v3
        with:
          name: jdk9db
          path: jdk9db
